// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/partitio/protoc-gen-gorm/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Age                  uint32               `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Num                  uint32               `protobuf:"varint,6,opt,name=num,proto3" json:"num,omitempty"`
	CreditCard           *CreditCard          `protobuf:"bytes,7,opt,name=credit_card,json=creditCard,proto3" json:"credit_card,omitempty"`
	Emails               []*Email             `protobuf:"bytes,8,rep,name=emails,proto3" json:"emails,omitempty"`
	Tasks                []*Task              `protobuf:"bytes,9,rep,name=tasks,proto3" json:"tasks,omitempty"`
	BillingAddress       *Address             `protobuf:"bytes,10,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	ShippingAddress      *Address             `protobuf:"bytes,11,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Languages            []*Language          `protobuf:"bytes,12,rep,name=languages,proto3" json:"languages,omitempty"`
	Friends              []*User              `protobuf:"bytes,13,rep,name=friends,proto3" json:"friends,omitempty"`
	ShippingAddressId    *resource.Identifier `protobuf:"bytes,14,opt,name=shipping_address_id,json=shippingAddressId,proto3" json:"shipping_address_id,omitempty"`
	ExternalUuid         *resource.Identifier `protobuf:"bytes,15,opt,name=external_uuid,json=externalUuid,proto3" json:"external_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a81b87a58f0b229, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *User) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *User) GetCreditCard() *CreditCard {
	if m != nil {
		return m.CreditCard
	}
	return nil
}

func (m *User) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *User) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *User) GetBillingAddress() *Address {
	if m != nil {
		return m.BillingAddress
	}
	return nil
}

func (m *User) GetShippingAddress() *Address {
	if m != nil {
		return m.ShippingAddress
	}
	return nil
}

func (m *User) GetLanguages() []*Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *User) GetFriends() []*User {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *User) GetShippingAddressId() *resource.Identifier {
	if m != nil {
		return m.ShippingAddressId
	}
	return nil
}

func (m *User) GetExternalUuid() *resource.Identifier {
	if m != nil {
		return m.ExternalUuid
	}
	return nil
}

type Email struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Subscribed           bool                 `protobuf:"varint,3,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	UserId               *resource.Identifier `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExternalNotNull      *resource.Identifier `protobuf:"bytes,5,opt,name=external_not_null,json=externalNotNull,proto3" json:"external_not_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a81b87a58f0b229, []int{1}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Email) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

func (m *Email) GetUserId() *resource.Identifier {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *Email) GetExternalNotNull() *resource.Identifier {
	if m != nil {
		return m.ExternalNotNull
	}
	return nil
}

type Address struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address_1            string               `protobuf:"bytes,2,opt,name=address_1,json=address1,proto3" json:"address_1,omitempty"`
	Address_2            string               `protobuf:"bytes,3,opt,name=address_2,json=address2,proto3" json:"address_2,omitempty"`
	Post                 string               `protobuf:"bytes,4,opt,name=post,proto3" json:"post,omitempty"`
	External             *resource.Identifier `protobuf:"bytes,5,opt,name=external,proto3" json:"external,omitempty"`
	ImplicitFk           *resource.Identifier `protobuf:"bytes,6,opt,name=implicit_fk,json=implicitFk,proto3" json:"implicit_fk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a81b87a58f0b229, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Address) GetAddress_1() string {
	if m != nil {
		return m.Address_1
	}
	return ""
}

func (m *Address) GetAddress_2() string {
	if m != nil {
		return m.Address_2
	}
	return ""
}

func (m *Address) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

func (m *Address) GetExternal() *resource.Identifier {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *Address) GetImplicitFk() *resource.Identifier {
	if m != nil {
		return m.ImplicitFk
	}
	return nil
}

type Language struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string               `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ExternalInt          *resource.Identifier `protobuf:"bytes,4,opt,name=external_int,json=externalInt,proto3" json:"external_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a81b87a58f0b229, []int{3}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Language) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Language) GetExternalInt() *resource.Identifier {
	if m != nil {
		return m.ExternalInt
	}
	return nil
}

type CreditCard struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Number               string               `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	UserId               *resource.Identifier `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreditCard) Reset()         { *m = CreditCard{} }
func (m *CreditCard) String() string { return proto.CompactTextString(m) }
func (*CreditCard) ProtoMessage()    {}
func (*CreditCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a81b87a58f0b229, []int{4}
}

func (m *CreditCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditCard.Unmarshal(m, b)
}
func (m *CreditCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditCard.Marshal(b, m, deterministic)
}
func (m *CreditCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditCard.Merge(m, src)
}
func (m *CreditCard) XXX_Size() int {
	return xxx_messageInfo_CreditCard.Size(m)
}
func (m *CreditCard) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditCard.DiscardUnknown(m)
}

var xxx_messageInfo_CreditCard proto.InternalMessageInfo

func (m *CreditCard) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreditCard) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreditCard) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CreditCard) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *CreditCard) GetUserId() *resource.Identifier {
	if m != nil {
		return m.UserId
	}
	return nil
}

type Task struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority             int64    `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a81b87a58f0b229, []int{5}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Email)(nil), "user.Email")
	proto.RegisterType((*Address)(nil), "user.Address")
	proto.RegisterType((*Language)(nil), "user.Language")
	proto.RegisterType((*CreditCard)(nil), "user.CreditCard")
	proto.RegisterType((*Task)(nil), "user.Task")
}

func init() { proto.RegisterFile("example/user/user.proto", fileDescriptor_5a81b87a58f0b229) }

var fileDescriptor_5a81b87a58f0b229 = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x5e, 0xe7, 0xd7, 0x39, 0x6e, 0x7e, 0x3a, 0xbb, 0x80, 0x53, 0x24, 0x88, 0xca, 0x4d, 0x85,
	0xa8, 0xa3, 0x06, 0xb6, 0xc0, 0x22, 0xa1, 0x36, 0xab, 0x22, 0x22, 0xd0, 0x4a, 0x8c, 0x76, 0x6f,
	0xb8, 0x89, 0xc6, 0x9e, 0x89, 0x3b, 0xc4, 0xf6, 0x58, 0x33, 0x63, 0xa9, 0x7b, 0xc9, 0x0b, 0xf0,
	0x1c, 0x88, 0x37, 0x48, 0xee, 0x78, 0x33, 0xe4, 0xf1, 0x4f, 0xad, 0x95, 0x48, 0x2b, 0xf6, 0x82,
	0x1b, 0xeb, 0xcc, 0x99, 0xef, 0x1c, 0x9f, 0xf3, 0xcd, 0x77, 0xc6, 0x86, 0x8f, 0xd8, 0x1d, 0x89,
	0xd3, 0x88, 0xcd, 0x33, 0xc5, 0xa4, 0x79, 0x78, 0xa9, 0x14, 0x5a, 0xa0, 0x4e, 0x6e, 0x9f, 0x5c,
	0x86, 0x5c, 0xdf, 0x66, 0xbe, 0x17, 0x88, 0x78, 0x9e, 0x12, 0xa9, 0xb9, 0xe6, 0x62, 0x6e, 0x00,
	0xc1, 0x79, 0xc8, 0x92, 0xf3, 0x50, 0xc8, 0x78, 0x2e, 0x52, 0xcd, 0x45, 0xa2, 0xe6, 0xf9, 0xa2,
	0x88, 0x3e, 0xf9, 0x34, 0x14, 0x22, 0x8c, 0x58, 0x01, 0xf5, 0xb3, 0xcd, 0x5c, 0xf3, 0x98, 0x29,
	0x4d, 0xe2, 0xb4, 0x04, 0xdc, 0x34, 0x12, 0xf3, 0x64, 0x23, 0xfc, 0x48, 0xdc, 0x89, 0x94, 0x25,
	0x73, 0xa2, 0x23, 0xa2, 0xce, 0x49, 0x9a, 0x9e, 0x6b, 0x21, 0xa2, 0x2d, 0xd7, 0x73, 0x99, 0x06,
	0x73, 0xc9, 0x94, 0xc8, 0x64, 0xc0, 0x6a, 0xa3, 0x48, 0x73, 0xfa, 0x67, 0x0f, 0x3a, 0x6f, 0x14,
	0x93, 0xe8, 0x39, 0xb4, 0x38, 0x75, 0xad, 0x99, 0x75, 0xe6, 0x2c, 0x3e, 0xf0, 0x4c, 0x12, 0x4f,
	0xa6, 0x81, 0xb7, 0xa2, 0x2c, 0xd1, 0x7c, 0xc3, 0x99, 0x5c, 0x8e, 0xf6, 0xbb, 0x29, 0x80, 0x8d,
	0x3a, 0x59, 0xc6, 0xe9, 0x99, 0x85, 0x5b, 0x9c, 0xa2, 0x6f, 0x01, 0x02, 0xc9, 0x88, 0x66, 0x74,
	0x4d, 0xb4, 0xdb, 0x32, 0xe1, 0x27, 0x5e, 0x51, 0xbc, 0x57, 0x15, 0xef, 0xbd, 0xae, 0x8a, 0xc7,
	0x83, 0x12, 0x7d, 0xad, 0xf3, 0xd0, 0x2c, 0xa5, 0x55, 0x68, 0xfb, 0xe1, 0xd0, 0x12, 0x7d, 0xad,
	0xd1, 0x25, 0xd8, 0x3e, 0x97, 0xfa, 0x96, 0x92, 0xb7, 0x6e, 0xe7, 0xc1, 0xc0, 0x1a, 0x8b, 0x5c,
	0x68, 0x93, 0x90, 0xb9, 0xdd, 0x99, 0x75, 0x36, 0x5c, 0xf6, 0xf6, 0xbb, 0x69, 0x6b, 0x62, 0xe1,
	0xdc, 0x85, 0x26, 0xd0, 0x4e, 0xb2, 0xd8, 0xed, 0xe5, 0x3b, 0x38, 0x37, 0xd1, 0x05, 0x38, 0x81,
	0x64, 0x94, 0xeb, 0x75, 0x40, 0x24, 0x75, 0xfb, 0xe6, 0x35, 0x13, 0xcf, 0x9c, 0xf0, 0x4b, 0xb3,
	0xf1, 0x92, 0x48, 0x8a, 0x21, 0xa8, 0x6d, 0xf4, 0x19, 0xf4, 0x58, 0x4c, 0x78, 0xa4, 0x5c, 0x7b,
	0xd6, 0x3e, 0x73, 0x16, 0x4e, 0x81, 0xbe, 0xc9, 0x7d, 0xb8, 0xdc, 0x42, 0x97, 0xd0, 0xd5, 0x44,
	0x6d, 0x95, 0x3b, 0x30, 0x18, 0x28, 0x30, 0xaf, 0x89, 0xda, 0x2e, 0x9f, 0xed, 0x77, 0xd3, 0xc9,
	0xe7, 0x23, 0xd4, 0xba, 0xb2, 0x4e, 0xed, 0x54, 0x72, 0x21, 0xb9, 0x7e, 0x8b, 0x0b, 0x38, 0xfa,
	0x1e, 0xc6, 0x3e, 0x8f, 0x22, 0x9e, 0x84, 0x6b, 0x42, 0xa9, 0x64, 0x4a, 0xb9, 0x60, 0x6a, 0x1a,
	0x16, 0x19, 0xae, 0x0b, 0x67, 0xd1, 0xd6, 0xe9, 0x13, 0x3c, 0x2a, 0xd1, 0xa5, 0x1f, 0x5d, 0xc1,
	0x44, 0xdd, 0xf2, 0x34, 0x6d, 0x26, 0x70, 0x0e, 0x25, 0x18, 0x57, 0xf0, 0x2a, 0xc3, 0x57, 0x30,
	0x88, 0x48, 0x12, 0x66, 0x24, 0x64, 0xca, 0x3d, 0x32, 0xd5, 0x8f, 0x8a, 0xd0, 0x9f, 0x4b, 0x77,
	0x11, 0xbb, 0x78, 0x82, 0xef, 0x81, 0xe8, 0x0b, 0xe8, 0x6f, 0x24, 0x67, 0x09, 0x55, 0xee, 0xb0,
	0xd9, 0x71, 0xae, 0xba, 0x1a, 0x5f, 0x41, 0xd0, 0x0d, 0x3c, 0x7d, 0xb7, 0xca, 0x35, 0xa7, 0xee,
	0xe8, 0x80, 0x2e, 0xf1, 0xf1, 0x3b, 0x85, 0xae, 0x28, 0xfa, 0x11, 0x86, 0xec, 0x4e, 0x33, 0x99,
	0x90, 0x68, 0x9d, 0xab, 0xd5, 0x1d, 0x1f, 0x12, 0xf6, 0xd1, 0x7e, 0x37, 0xb5, 0xa1, 0x57, 0x08,
	0x1b, 0x1f, 0x55, 0x91, 0x6f, 0x32, 0x4e, 0x5f, 0xd8, 0xfb, 0xdd, 0xb4, 0x63, 0x5b, 0x33, 0xeb,
	0xf4, 0xf7, 0x16, 0x74, 0xcd, 0x51, 0xfe, 0xd7, 0x59, 0x79, 0x06, 0x5d, 0xa3, 0x01, 0x33, 0x26,
	0x03, 0x5c, 0x2c, 0xd0, 0x27, 0x00, 0x2a, 0xf3, 0x55, 0x20, 0xb9, 0xcf, 0xa8, 0x19, 0x03, 0x1b,
	0x37, 0x3c, 0xc8, 0x83, 0x7e, 0xce, 0x57, 0xce, 0x42, 0xe7, 0x10, 0x0b, 0xbd, 0x1c, 0xb5, 0xa2,
	0xe8, 0x17, 0x38, 0xae, 0x5b, 0x4f, 0x84, 0x5e, 0x27, 0x59, 0x14, 0x19, 0xc5, 0x3f, 0xae, 0xd6,
	0x2b, 0x0b, 0x8f, 0xab, 0xf8, 0x57, 0x42, 0xbf, 0xca, 0xa2, 0xa8, 0xc1, 0xc1, 0x5f, 0x2d, 0xe8,
	0x57, 0x72, 0xf8, 0xe6, 0x61, 0x16, 0x8e, 0xf7, 0xbb, 0xe9, 0x10, 0x1c, 0xd4, 0xe7, 0x89, 0x66,
	0x21, 0x93, 0x25, 0x11, 0x1f, 0xc3, 0xa0, 0x3a, 0xdb, 0x8b, 0x92, 0x0c, 0xbb, 0x74, 0x5c, 0x34,
	0x37, 0x17, 0x86, 0x8e, 0xfb, 0xcd, 0x05, 0x42, 0xd0, 0x49, 0x85, 0xd2, 0x86, 0x89, 0x01, 0x36,
	0x36, 0xba, 0x02, 0xbb, 0x2a, 0xf8, 0x70, 0x9f, 0xc3, 0xfd, 0x6e, 0x3a, 0x80, 0x3e, 0xea, 0xfe,
	0xa6, 0x44, 0xe2, 0xe3, 0x3a, 0x0a, 0xfd, 0x04, 0x0e, 0x8f, 0xd3, 0x88, 0x07, 0x5c, 0xaf, 0x37,
	0x5b, 0x73, 0x09, 0xfc, 0x6b, 0x92, 0xa7, 0xfb, 0xdd, 0x74, 0x9c, 0x6b, 0x45, 0xb3, 0x3b, 0xfd,
	0xa2, 0x10, 0x04, 0x86, 0x2a, 0xfc, 0x87, 0x6d, 0x83, 0xac, 0xbf, 0x2d, 0xb0, 0xab, 0xc9, 0x78,
	0x0f, 0xb6, 0x10, 0x74, 0x12, 0x12, 0xb3, 0x92, 0x28, 0x63, 0xe7, 0xbe, 0x40, 0x50, 0x56, 0xf2,
	0x63, 0x6c, 0xb4, 0x82, 0x5a, 0xb9, 0x6b, 0x9e, 0xe8, 0x83, 0x6a, 0x59, 0x8e, 0xf7, 0xbb, 0xa9,
	0x03, 0x83, 0xfa, 0x5d, 0xd8, 0xa9, 0x62, 0x57, 0x89, 0x6e, 0xf4, 0xf0, 0x47, 0x0b, 0xe0, 0xfe,
	0xb6, 0x7b, 0x8f, 0x2e, 0xfe, 0x9f, 0x0f, 0xc5, 0x87, 0xd0, 0x4b, 0xb2, 0xd8, 0x67, 0xb2, 0x54,
	0x4c, 0xb9, 0x6a, 0x0e, 0x55, 0xf7, 0x11, 0x43, 0xd5, 0x20, 0xc4, 0x87, 0x4e, 0x7e, 0x57, 0xd7,
	0xa7, 0x62, 0x35, 0x4e, 0x65, 0x06, 0x0e, 0x65, 0xf9, 0xdc, 0x9a, 0xef, 0x79, 0x79, 0x60, 0x4d,
	0x17, 0x3a, 0x81, 0xfa, 0x5e, 0x37, 0x8d, 0xb4, 0x71, 0xbd, 0xbe, 0x7f, 0xc7, 0xf2, 0xeb, 0x5f,
	0x9f, 0x3f, 0xe6, 0xb7, 0xa1, 0xf9, 0xe7, 0xf1, 0x5d, 0xfe, 0xf0, 0x7b, 0x06, 0xf2, 0xe5, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0x6f, 0x89, 0xe5, 0x95, 0x08, 0x00, 0x00,
}
