// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: example/feature_demo/demo_types.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/partitio/protoc-gen-gorm/options"
import _ "github.com/partitio/protoc-gen-gorm/types"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/partitio/protoc-gen-gorm/example/user"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
