// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/feature_demo/demo_multi_file_service.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	_ "github.com/partitio/protoc-gen-gorm/options"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadAccountRequest struct {
	// For a read request, the id field is the only to be specified
	Id                   uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadAccountRequest) Reset()         { *m = ReadAccountRequest{} }
func (m *ReadAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRequest) ProtoMessage()    {}
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df6cba6b16e2ef, []int{0}
}

func (m *ReadAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRequest.Unmarshal(m, b)
}
func (m *ReadAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRequest.Marshal(b, m, deterministic)
}
func (m *ReadAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRequest.Merge(m, src)
}
func (m *ReadAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRequest.Size(m)
}
func (m *ReadAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRequest proto.InternalMessageInfo

func (m *ReadAccountRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadAccountRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadBlogPostsResponse struct {
	Posts                []*BlogPost `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadBlogPostsResponse) Reset()         { *m = ReadBlogPostsResponse{} }
func (m *ReadBlogPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlogPostsResponse) ProtoMessage()    {}
func (*ReadBlogPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df6cba6b16e2ef, []int{1}
}

func (m *ReadBlogPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogPostsResponse.Unmarshal(m, b)
}
func (m *ReadBlogPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogPostsResponse.Marshal(b, m, deterministic)
}
func (m *ReadBlogPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogPostsResponse.Merge(m, src)
}
func (m *ReadBlogPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlogPostsResponse.Size(m)
}
func (m *ReadBlogPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogPostsResponse proto.InternalMessageInfo

func (m *ReadBlogPostsResponse) GetPosts() []*BlogPost {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadAccountRequest)(nil), "example.ReadAccountRequest")
	proto.RegisterType((*ReadBlogPostsResponse)(nil), "example.ReadBlogPostsResponse")
}

func init() {
	proto.RegisterFile("example/feature_demo/demo_multi_file_service.proto", fileDescriptor_93df6cba6b16e2ef)
}

var fileDescriptor_93df6cba6b16e2ef = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4b, 0xe3, 0x40,
	0x14, 0xc7, 0x49, 0xb6, 0xdb, 0x5d, 0xa6, 0xb0, 0x8b, 0x01, 0xa1, 0x46, 0x91, 0xd2, 0x8b, 0x45,
	0x48, 0x06, 0xa2, 0x78, 0xf1, 0x52, 0x2b, 0x78, 0xf0, 0x24, 0xe9, 0xad, 0x07, 0xc3, 0x34, 0x79,
	0x89, 0x83, 0x93, 0xbc, 0xe9, 0xcc, 0x8b, 0xd4, 0x3f, 0x4d, 0xff, 0x3a, 0x49, 0x93, 0x8a, 0x52,
	0x0f, 0xbd, 0x0c, 0xcc, 0xfb, 0xfe, 0xe0, 0x33, 0x6f, 0x58, 0x04, 0x6b, 0x51, 0x6a, 0x05, 0x3c,
	0x07, 0x41, 0xb5, 0x81, 0x24, 0x83, 0x12, 0x79, 0x73, 0x24, 0x65, 0xad, 0x48, 0x26, 0xb9, 0x54,
	0x90, 0x58, 0x30, 0x2f, 0x32, 0x85, 0x50, 0x1b, 0x24, 0xf4, 0xfe, 0x74, 0x19, 0xff, 0xaa, 0x90,
	0xf4, 0x54, 0x2f, 0xc3, 0x14, 0x4b, 0xae, 0x85, 0x21, 0x49, 0x12, 0xf9, 0xc6, 0x93, 0x06, 0x05,
	0x54, 0x41, 0x81, 0xa6, 0xe4, 0xa8, 0x49, 0x62, 0x65, 0x79, 0x73, 0x69, 0x0b, 0xfc, 0xfb, 0x2f,
	0x39, 0x59, 0xe5, 0xb8, 0x54, 0xb8, 0x46, 0x0d, 0x15, 0x17, 0xa4, 0x84, 0x0d, 0x84, 0xd6, 0x01,
	0x21, 0xaa, 0x67, 0x49, 0x7c, 0x55, 0x83, 0x79, 0xe5, 0x29, 0x2a, 0x05, 0x69, 0xd3, 0x93, 0xa0,
	0x06, 0x23, 0x08, 0x8d, 0xed, 0xba, 0xce, 0xf7, 0x79, 0x40, 0xeb, 0x1d, 0x2f, 0x98, 0x17, 0x83,
	0xc8, 0x6e, 0xd2, 0x14, 0xeb, 0x8a, 0x62, 0x58, 0xd5, 0x60, 0xc9, 0xfb, 0xc7, 0x5c, 0x99, 0x0d,
	0x9d, 0x91, 0x33, 0xe9, 0xc5, 0xae, 0xcc, 0xbc, 0x4b, 0xd6, 0xcf, 0x25, 0xa8, 0xcc, 0x0e, 0xdd,
	0x91, 0x33, 0x19, 0x44, 0x27, 0xe1, 0x96, 0x31, 0x14, 0x5a, 0x86, 0x77, 0x8d, 0x36, 0x87, 0x8e,
	0x27, 0xee, 0xbc, 0xe3, 0x29, 0x3b, 0x6c, 0xba, 0x67, 0x0a, 0x8b, 0x07, 0xb4, 0x64, 0x63, 0xb0,
	0x1a, 0x2b, 0x0b, 0xde, 0x19, 0xfb, 0xad, 0x9b, 0xc1, 0xd0, 0x19, 0xfd, 0x9a, 0x0c, 0xa2, 0x83,
	0xb0, 0x03, 0x0e, 0xb7, 0xd6, 0xb8, 0xd5, 0xa3, 0x47, 0xf6, 0x7f, 0x3b, 0x9a, 0xb7, 0xfb, 0xf6,
	0x6e, 0x59, 0xaf, 0x29, 0xf5, 0x8e, 0x3f, 0x43, 0xbb, 0xfc, 0xfe, 0xe9, 0x37, 0x71, 0x07, 0xc0,
	0xef, 0xbf, 0xbf, 0x1d, 0xb9, 0x7f, 0x9d, 0xd9, 0x6c, 0x31, 0xdd, 0xe7, 0xbf, 0x7e, 0xda, 0xe7,
	0x75, 0x37, 0x5c, 0xf6, 0x37, 0xee, 0x8b, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x58, 0x18,
	0xa3, 0x37, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogPostServiceClient is the client API for BlogPostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogPostServiceClient interface {
	Read(ctx context.Context, in *ReadAccountRequest, opts ...grpc.CallOption) (*ReadBlogPostsResponse, error)
}

type blogPostServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogPostServiceClient(cc *grpc.ClientConn) BlogPostServiceClient {
	return &blogPostServiceClient{cc}
}

func (c *blogPostServiceClient) Read(ctx context.Context, in *ReadAccountRequest, opts ...grpc.CallOption) (*ReadBlogPostsResponse, error) {
	out := new(ReadBlogPostsResponse)
	err := c.cc.Invoke(ctx, "/example.BlogPostService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogPostServiceServer is the server API for BlogPostService service.
type BlogPostServiceServer interface {
	Read(context.Context, *ReadAccountRequest) (*ReadBlogPostsResponse, error)
}

func RegisterBlogPostServiceServer(s *grpc.Server, srv BlogPostServiceServer) {
	s.RegisterService(&_BlogPostService_serviceDesc, srv)
}

func _BlogPostService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.BlogPostService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).Read(ctx, req.(*ReadAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogPostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.BlogPostService",
	HandlerType: (*BlogPostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _BlogPostService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/feature_demo/demo_multi_file_service.proto",
}
