// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/feature_demo/demo_service.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	query "github.com/partitio/atlas-app-toolkit/query"
	_ "github.com/partitio/protoc-gen-gorm/options"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// IntPoint is a basic message type representing a single cartesian point
// that we want to store in a database
type IntPoint struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntPoint) Reset()         { *m = IntPoint{} }
func (m *IntPoint) String() string { return proto.CompactTextString(m) }
func (*IntPoint) ProtoMessage()    {}
func (*IntPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{0}
}

func (m *IntPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntPoint.Unmarshal(m, b)
}
func (m *IntPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntPoint.Marshal(b, m, deterministic)
}
func (m *IntPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntPoint.Merge(m, src)
}
func (m *IntPoint) XXX_Size() int {
	return xxx_messageInfo_IntPoint.Size(m)
}
func (m *IntPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_IntPoint.DiscardUnknown(m)
}

var xxx_messageInfo_IntPoint proto.InternalMessageInfo

func (m *IntPoint) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IntPoint) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *IntPoint) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type CreateIntPointRequest struct {
	// Convention dictates that this field be of the given type, and be
	// named 'payload' in order to autogenerate the handler
	Payload              *IntPoint `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateIntPointRequest) Reset()         { *m = CreateIntPointRequest{} }
func (m *CreateIntPointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIntPointRequest) ProtoMessage()    {}
func (*CreateIntPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{1}
}

func (m *CreateIntPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIntPointRequest.Unmarshal(m, b)
}
func (m *CreateIntPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIntPointRequest.Marshal(b, m, deterministic)
}
func (m *CreateIntPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIntPointRequest.Merge(m, src)
}
func (m *CreateIntPointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIntPointRequest.Size(m)
}
func (m *CreateIntPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIntPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIntPointRequest proto.InternalMessageInfo

func (m *CreateIntPointRequest) GetPayload() *IntPoint {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateIntPointResponse struct {
	// Convention also requires that the return type be the same and named 'result'
	Result               *IntPoint `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateIntPointResponse) Reset()         { *m = CreateIntPointResponse{} }
func (m *CreateIntPointResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIntPointResponse) ProtoMessage()    {}
func (*CreateIntPointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{2}
}

func (m *CreateIntPointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIntPointResponse.Unmarshal(m, b)
}
func (m *CreateIntPointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIntPointResponse.Marshal(b, m, deterministic)
}
func (m *CreateIntPointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIntPointResponse.Merge(m, src)
}
func (m *CreateIntPointResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIntPointResponse.Size(m)
}
func (m *CreateIntPointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIntPointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIntPointResponse proto.InternalMessageInfo

func (m *CreateIntPointResponse) GetResult() *IntPoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadIntPointRequest struct {
	// For a read request, the id field is the only to be specified
	Id                   uint32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadIntPointRequest) Reset()         { *m = ReadIntPointRequest{} }
func (m *ReadIntPointRequest) String() string { return proto.CompactTextString(m) }
func (*ReadIntPointRequest) ProtoMessage()    {}
func (*ReadIntPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{3}
}

func (m *ReadIntPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadIntPointRequest.Unmarshal(m, b)
}
func (m *ReadIntPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadIntPointRequest.Marshal(b, m, deterministic)
}
func (m *ReadIntPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadIntPointRequest.Merge(m, src)
}
func (m *ReadIntPointRequest) XXX_Size() int {
	return xxx_messageInfo_ReadIntPointRequest.Size(m)
}
func (m *ReadIntPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadIntPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadIntPointRequest proto.InternalMessageInfo

func (m *ReadIntPointRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadIntPointRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadIntPointResponse struct {
	// Again the type with 'result' name
	Result               *IntPoint `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadIntPointResponse) Reset()         { *m = ReadIntPointResponse{} }
func (m *ReadIntPointResponse) String() string { return proto.CompactTextString(m) }
func (*ReadIntPointResponse) ProtoMessage()    {}
func (*ReadIntPointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{4}
}

func (m *ReadIntPointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadIntPointResponse.Unmarshal(m, b)
}
func (m *ReadIntPointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadIntPointResponse.Marshal(b, m, deterministic)
}
func (m *ReadIntPointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadIntPointResponse.Merge(m, src)
}
func (m *ReadIntPointResponse) XXX_Size() int {
	return xxx_messageInfo_ReadIntPointResponse.Size(m)
}
func (m *ReadIntPointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadIntPointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadIntPointResponse proto.InternalMessageInfo

func (m *ReadIntPointResponse) GetResult() *IntPoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateIntPointRequest struct {
	Payload              *IntPoint             `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	GerogeriGegege       *field_mask.FieldMask `protobuf:"bytes,2,opt,name=gerogeri_gegege,json=gerogeriGegege,proto3" json:"gerogeri_gegege,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateIntPointRequest) Reset()         { *m = UpdateIntPointRequest{} }
func (m *UpdateIntPointRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIntPointRequest) ProtoMessage()    {}
func (*UpdateIntPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{5}
}

func (m *UpdateIntPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIntPointRequest.Unmarshal(m, b)
}
func (m *UpdateIntPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIntPointRequest.Marshal(b, m, deterministic)
}
func (m *UpdateIntPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIntPointRequest.Merge(m, src)
}
func (m *UpdateIntPointRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateIntPointRequest.Size(m)
}
func (m *UpdateIntPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIntPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIntPointRequest proto.InternalMessageInfo

func (m *UpdateIntPointRequest) GetPayload() *IntPoint {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateIntPointRequest) GetGerogeriGegege() *field_mask.FieldMask {
	if m != nil {
		return m.GerogeriGegege
	}
	return nil
}

type UpdateIntPointResponse struct {
	Result               *IntPoint `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateIntPointResponse) Reset()         { *m = UpdateIntPointResponse{} }
func (m *UpdateIntPointResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateIntPointResponse) ProtoMessage()    {}
func (*UpdateIntPointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{6}
}

func (m *UpdateIntPointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIntPointResponse.Unmarshal(m, b)
}
func (m *UpdateIntPointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIntPointResponse.Marshal(b, m, deterministic)
}
func (m *UpdateIntPointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIntPointResponse.Merge(m, src)
}
func (m *UpdateIntPointResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateIntPointResponse.Size(m)
}
func (m *UpdateIntPointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIntPointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIntPointResponse proto.InternalMessageInfo

func (m *UpdateIntPointResponse) GetResult() *IntPoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteIntPointRequest struct {
	// Only the id is needed for a delete request
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIntPointRequest) Reset()         { *m = DeleteIntPointRequest{} }
func (m *DeleteIntPointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIntPointRequest) ProtoMessage()    {}
func (*DeleteIntPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{7}
}

func (m *DeleteIntPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIntPointRequest.Unmarshal(m, b)
}
func (m *DeleteIntPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIntPointRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIntPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIntPointRequest.Merge(m, src)
}
func (m *DeleteIntPointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIntPointRequest.Size(m)
}
func (m *DeleteIntPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIntPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIntPointRequest proto.InternalMessageInfo

func (m *DeleteIntPointRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteIntPointsRequest struct {
	// Only the id is needed for a delete request
	Ids                  []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIntPointsRequest) Reset()         { *m = DeleteIntPointsRequest{} }
func (m *DeleteIntPointsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIntPointsRequest) ProtoMessage()    {}
func (*DeleteIntPointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{8}
}

func (m *DeleteIntPointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIntPointsRequest.Unmarshal(m, b)
}
func (m *DeleteIntPointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIntPointsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIntPointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIntPointsRequest.Merge(m, src)
}
func (m *DeleteIntPointsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIntPointsRequest.Size(m)
}
func (m *DeleteIntPointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIntPointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIntPointsRequest proto.InternalMessageInfo

func (m *DeleteIntPointsRequest) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

// By convention, on DELETE no response data is given, so either a
// google.protobuf.empty, or an empty struct is sufficient
type DeleteIntPointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIntPointResponse) Reset()         { *m = DeleteIntPointResponse{} }
func (m *DeleteIntPointResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIntPointResponse) ProtoMessage()    {}
func (*DeleteIntPointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{9}
}

func (m *DeleteIntPointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIntPointResponse.Unmarshal(m, b)
}
func (m *DeleteIntPointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIntPointResponse.Marshal(b, m, deterministic)
}
func (m *DeleteIntPointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIntPointResponse.Merge(m, src)
}
func (m *DeleteIntPointResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIntPointResponse.Size(m)
}
func (m *DeleteIntPointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIntPointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIntPointResponse proto.InternalMessageInfo

type ListIntPointResponse struct {
	// Note repeated field and plural name 'results'
	Results              []*IntPoint     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PageInfo             *query.PageInfo `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListIntPointResponse) Reset()         { *m = ListIntPointResponse{} }
func (m *ListIntPointResponse) String() string { return proto.CompactTextString(m) }
func (*ListIntPointResponse) ProtoMessage()    {}
func (*ListIntPointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{10}
}

func (m *ListIntPointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIntPointResponse.Unmarshal(m, b)
}
func (m *ListIntPointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIntPointResponse.Marshal(b, m, deterministic)
}
func (m *ListIntPointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIntPointResponse.Merge(m, src)
}
func (m *ListIntPointResponse) XXX_Size() int {
	return xxx_messageInfo_ListIntPointResponse.Size(m)
}
func (m *ListIntPointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIntPointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIntPointResponse proto.InternalMessageInfo

func (m *ListIntPointResponse) GetResults() []*IntPoint {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListIntPointResponse) GetPageInfo() *query.PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

type ListSomethingResponse struct {
	// Note repeated field and plural name 'results'
	Results              []*Something    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PageInfo             *query.PageInfo `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSomethingResponse) Reset()         { *m = ListSomethingResponse{} }
func (m *ListSomethingResponse) String() string { return proto.CompactTextString(m) }
func (*ListSomethingResponse) ProtoMessage()    {}
func (*ListSomethingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{11}
}

func (m *ListSomethingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSomethingResponse.Unmarshal(m, b)
}
func (m *ListSomethingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSomethingResponse.Marshal(b, m, deterministic)
}
func (m *ListSomethingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSomethingResponse.Merge(m, src)
}
func (m *ListSomethingResponse) XXX_Size() int {
	return xxx_messageInfo_ListSomethingResponse.Size(m)
}
func (m *ListSomethingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSomethingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSomethingResponse proto.InternalMessageInfo

func (m *ListSomethingResponse) GetResults() []*Something {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListSomethingResponse) GetPageInfo() *query.PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

// A dummy type to demo an rpc that can't be autogenerated
type Something struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Something) Reset()         { *m = Something{} }
func (m *Something) String() string { return proto.CompactTextString(m) }
func (*Something) ProtoMessage()    {}
func (*Something) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{12}
}

func (m *Something) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Something.Unmarshal(m, b)
}
func (m *Something) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Something.Marshal(b, m, deterministic)
}
func (m *Something) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Something.Merge(m, src)
}
func (m *Something) XXX_Size() int {
	return xxx_messageInfo_Something.Size(m)
}
func (m *Something) XXX_DiscardUnknown() {
	xxx_messageInfo_Something.DiscardUnknown(m)
}

var xxx_messageInfo_Something proto.InternalMessageInfo

func (m *Something) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type ListIntPointRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListIntPointRequest) Reset()         { *m = ListIntPointRequest{} }
func (m *ListIntPointRequest) String() string { return proto.CompactTextString(m) }
func (*ListIntPointRequest) ProtoMessage()    {}
func (*ListIntPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{13}
}

func (m *ListIntPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIntPointRequest.Unmarshal(m, b)
}
func (m *ListIntPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIntPointRequest.Marshal(b, m, deterministic)
}
func (m *ListIntPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIntPointRequest.Merge(m, src)
}
func (m *ListIntPointRequest) XXX_Size() int {
	return xxx_messageInfo_ListIntPointRequest.Size(m)
}
func (m *ListIntPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIntPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIntPointRequest proto.InternalMessageInfo

func (m *ListIntPointRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListIntPointRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListIntPointRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListIntPointRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type Circle struct {
	R                    uint32   `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circle) Reset()         { *m = Circle{} }
func (m *Circle) String() string { return proto.CompactTextString(m) }
func (*Circle) ProtoMessage()    {}
func (*Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{14}
}

func (m *Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circle.Unmarshal(m, b)
}
func (m *Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circle.Marshal(b, m, deterministic)
}
func (m *Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circle.Merge(m, src)
}
func (m *Circle) XXX_Size() int {
	return xxx_messageInfo_Circle.Size(m)
}
func (m *Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Circle proto.InternalMessageInfo

func (m *Circle) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

type ListCircleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCircleRequest) Reset()         { *m = ListCircleRequest{} }
func (m *ListCircleRequest) String() string { return proto.CompactTextString(m) }
func (*ListCircleRequest) ProtoMessage()    {}
func (*ListCircleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{15}
}

func (m *ListCircleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCircleRequest.Unmarshal(m, b)
}
func (m *ListCircleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCircleRequest.Marshal(b, m, deterministic)
}
func (m *ListCircleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCircleRequest.Merge(m, src)
}
func (m *ListCircleRequest) XXX_Size() int {
	return xxx_messageInfo_ListCircleRequest.Size(m)
}
func (m *ListCircleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCircleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCircleRequest proto.InternalMessageInfo

type ListCircleResponse struct {
	Results              []*Circle `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListCircleResponse) Reset()         { *m = ListCircleResponse{} }
func (m *ListCircleResponse) String() string { return proto.CompactTextString(m) }
func (*ListCircleResponse) ProtoMessage()    {}
func (*ListCircleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76556502a10778a5, []int{16}
}

func (m *ListCircleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCircleResponse.Unmarshal(m, b)
}
func (m *ListCircleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCircleResponse.Marshal(b, m, deterministic)
}
func (m *ListCircleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCircleResponse.Merge(m, src)
}
func (m *ListCircleResponse) XXX_Size() int {
	return xxx_messageInfo_ListCircleResponse.Size(m)
}
func (m *ListCircleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCircleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCircleResponse proto.InternalMessageInfo

func (m *ListCircleResponse) GetResults() []*Circle {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*IntPoint)(nil), "example.IntPoint")
	proto.RegisterType((*CreateIntPointRequest)(nil), "example.CreateIntPointRequest")
	proto.RegisterType((*CreateIntPointResponse)(nil), "example.CreateIntPointResponse")
	proto.RegisterType((*ReadIntPointRequest)(nil), "example.ReadIntPointRequest")
	proto.RegisterType((*ReadIntPointResponse)(nil), "example.ReadIntPointResponse")
	proto.RegisterType((*UpdateIntPointRequest)(nil), "example.UpdateIntPointRequest")
	proto.RegisterType((*UpdateIntPointResponse)(nil), "example.UpdateIntPointResponse")
	proto.RegisterType((*DeleteIntPointRequest)(nil), "example.DeleteIntPointRequest")
	proto.RegisterType((*DeleteIntPointsRequest)(nil), "example.DeleteIntPointsRequest")
	proto.RegisterType((*DeleteIntPointResponse)(nil), "example.DeleteIntPointResponse")
	proto.RegisterType((*ListIntPointResponse)(nil), "example.ListIntPointResponse")
	proto.RegisterType((*ListSomethingResponse)(nil), "example.ListSomethingResponse")
	proto.RegisterType((*Something)(nil), "example.Something")
	proto.RegisterType((*ListIntPointRequest)(nil), "example.ListIntPointRequest")
	proto.RegisterType((*Circle)(nil), "example.Circle")
	proto.RegisterType((*ListCircleRequest)(nil), "example.ListCircleRequest")
	proto.RegisterType((*ListCircleResponse)(nil), "example.ListCircleResponse")
}

func init() {
	proto.RegisterFile("example/feature_demo/demo_service.proto", fileDescriptor_76556502a10778a5)
}

var fileDescriptor_76556502a10778a5 = []byte{
	// 919 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xd1, 0x6e, 0xdb, 0x36,
	0x14, 0xb5, 0x12, 0xd7, 0xb1, 0x6f, 0x9a, 0xb8, 0x65, 0xe2, 0xcc, 0x51, 0xbb, 0x2c, 0xd0, 0x4b,
	0xd3, 0x75, 0x91, 0x0a, 0x77, 0xd8, 0xc3, 0x0a, 0x6c, 0x6d, 0xdc, 0x76, 0x08, 0xba, 0x02, 0x85,
	0xbc, 0x3d, 0x2c, 0x03, 0x66, 0xd0, 0x16, 0xad, 0x10, 0x91, 0x45, 0x95, 0xa2, 0x07, 0x7b, 0x7f,
	0xb0, 0x4f, 0x4a, 0xbe, 0x66, 0x4f, 0xfb, 0x88, 0x3d, 0x0d, 0x14, 0x29, 0x45, 0x92, 0x65, 0x20,
	0x5d, 0x06, 0xec, 0x65, 0x30, 0x60, 0x88, 0xe4, 0xb9, 0x97, 0xf7, 0x1e, 0x1e, 0x1e, 0x09, 0x1e,
	0x91, 0x39, 0x9e, 0x46, 0x01, 0x71, 0x26, 0x04, 0x8b, 0x19, 0x27, 0x43, 0x8f, 0x4c, 0x99, 0x23,
	0xff, 0x86, 0x31, 0xe1, 0xbf, 0xd2, 0x31, 0xb1, 0x23, 0xce, 0x04, 0x43, 0x1b, 0x1a, 0x68, 0x3e,
	0xf0, 0x19, 0xf3, 0x03, 0xe2, 0x24, 0xd3, 0xa3, 0xd9, 0xc4, 0x21, 0xd3, 0x48, 0x2c, 0x14, 0xca,
	0xfc, 0xca, 0xa7, 0xe2, 0x7c, 0x36, 0xb2, 0xc7, 0x6c, 0xea, 0x44, 0x98, 0x0b, 0x2a, 0x28, 0x53,
	0xc8, 0xf1, 0xb1, 0x4f, 0xc2, 0x63, 0x9f, 0xf1, 0xa9, 0xc3, 0x22, 0x41, 0x59, 0x18, 0x3b, 0x72,
	0xa0, 0xe3, 0x0e, 0xcb, 0x49, 0x27, 0x94, 0x04, 0xde, 0x70, 0x8a, 0xe3, 0x0b, 0x8d, 0x78, 0x53,
	0x95, 0x19, 0x8b, 0x00, 0xc7, 0xc7, 0x38, 0x8a, 0x8e, 0x05, 0x63, 0xc1, 0x05, 0x15, 0xce, 0x87,
	0x19, 0xe1, 0x0b, 0x67, 0xcc, 0x82, 0x80, 0x8c, 0xe5, 0x2e, 0x43, 0x16, 0x11, 0x8e, 0x05, 0xe3,
	0xb1, 0xca, 0x63, 0x7d, 0x03, 0xcd, 0xd3, 0x50, 0xbc, 0x67, 0x34, 0x14, 0x68, 0x1b, 0xd6, 0xa8,
	0xd7, 0x35, 0x0e, 0x8d, 0xa3, 0x2d, 0x77, 0x8d, 0x7a, 0xe8, 0x2e, 0x18, 0xf3, 0xee, 0xda, 0xa1,
	0x71, 0x74, 0xc7, 0x35, 0xe6, 0x72, 0xb4, 0xe8, 0xae, 0xab, 0xd1, 0xe2, 0xeb, 0xc6, 0xd5, 0xe5,
	0xfe, 0x5a, 0xd3, 0xb0, 0x5e, 0x41, 0xa7, 0xcf, 0x09, 0x16, 0x24, 0xcd, 0xe2, 0x92, 0x0f, 0x33,
	0x12, 0x0b, 0xf4, 0x04, 0x36, 0x22, 0xbc, 0x08, 0x18, 0x56, 0x19, 0x37, 0x7b, 0xf7, 0x6d, 0x4d,
	0x99, 0x9d, 0x41, 0x53, 0x84, 0xd5, 0x87, 0xbd, 0x72, 0x96, 0x38, 0x62, 0x61, 0x4c, 0xd0, 0x63,
	0x68, 0x70, 0x12, 0xcf, 0x02, 0xb1, 0x3a, 0x8b, 0x06, 0x58, 0x3f, 0xc3, 0x8e, 0x4b, 0xb0, 0x57,
	0x2e, 0xa4, 0xdc, 0xd5, 0x97, 0xd0, 0x48, 0xd8, 0x8c, 0x93, 0xd6, 0x36, 0x7b, 0x0f, 0x6d, 0x1a,
	0x4e, 0xd8, 0x28, 0x60, 0x73, 0x1b, 0x47, 0xd4, 0x7e, 0x23, 0xd7, 0x06, 0x44, 0xf3, 0xe5, 0x6a,
	0xac, 0xf5, 0x12, 0x76, 0x8b, 0xc9, 0x3f, 0xbe, 0xbe, 0xdf, 0x0d, 0xe8, 0xfc, 0x18, 0x79, 0xb7,
	0xe4, 0x0a, 0xf5, 0xa1, 0xed, 0x13, 0xce, 0x7c, 0xc2, 0xe9, 0xd0, 0x27, 0xf2, 0xa7, 0x1b, 0x31,
	0x6d, 0xa5, 0x1a, 0x3b, 0x55, 0x8d, 0xea, 0xe5, 0x1d, 0x8e, 0x2f, 0xdc, 0xed, 0x34, 0xe4, 0xbb,
	0x24, 0x42, 0x12, 0x5e, 0x2e, 0xe5, 0xe3, 0x1b, 0x7a, 0x04, 0x9d, 0x57, 0x24, 0x20, 0xcb, 0xfd,
	0x94, 0x28, 0xb7, 0x3e, 0x87, 0xbd, 0x22, 0x30, 0x4e, 0x91, 0xf7, 0x60, 0x9d, 0x7a, 0x71, 0xd7,
	0x38, 0x5c, 0x3f, 0xda, 0x72, 0xe5, 0xa3, 0xd5, 0x2d, 0x63, 0xd3, 0xca, 0xac, 0x39, 0xec, 0x7e,
	0x4f, 0x63, 0xb1, 0x54, 0xf1, 0x13, 0xd8, 0x50, 0x05, 0xa9, 0x3c, 0xd5, 0xec, 0x69, 0x04, 0x7a,
	0x06, 0xad, 0x08, 0xfb, 0x64, 0x28, 0xcf, 0x5c, 0xf3, 0xb6, 0x57, 0x14, 0xc0, 0x7b, 0xec, 0x93,
	0xd3, 0x70, 0xc2, 0xdc, 0x66, 0xa4, 0x9f, 0xac, 0xdf, 0xa0, 0x23, 0x77, 0x1e, 0xb0, 0x29, 0x11,
	0xe7, 0x34, 0xf4, 0xb3, 0xad, 0xbf, 0x28, 0x6f, 0x8d, 0xb2, 0xad, 0xaf, 0xc1, 0xb7, 0xdb, 0xfb,
	0x31, 0xb4, 0xb2, 0x54, 0x68, 0x17, 0xee, 0x24, 0x7a, 0x4c, 0xb8, 0x6d, 0xb9, 0x6a, 0x90, 0xdd,
	0xc5, 0x3f, 0x0c, 0xd8, 0x29, 0x32, 0xa4, 0x48, 0x76, 0xa4, 0xe2, 0x03, 0x41, 0xb8, 0x3e, 0xd2,
	0x4f, 0xca, 0x8a, 0x97, 0x6b, 0xb2, 0x52, 0x0d, 0x43, 0x4f, 0xa1, 0xc9, 0xb8, 0x47, 0xf8, 0x70,
	0xb4, 0xd0, 0x75, 0x76, 0x8a, 0x21, 0x03, 0xc6, 0x45, 0xd2, 0x5a, 0x02, 0x3b, 0x59, 0xe4, 0x2e,
	0xd5, 0xfa, 0xcd, 0x2f, 0x15, 0x7a, 0x0a, 0x8d, 0x08, 0xfb, 0x34, 0xf4, 0xbb, 0xf5, 0x24, 0xaa,
	0xbb, 0xc4, 0x06, 0x0d, 0xb1, 0x8a, 0x50, 0x38, 0xeb, 0x00, 0x1a, 0x7d, 0xca, 0xc7, 0x01, 0x91,
	0x76, 0xc4, 0xb5, 0xc4, 0x0c, 0x9e, 0x51, 0xb0, 0x03, 0xf7, 0x25, 0x03, 0x0a, 0xa3, 0xfb, 0xb7,
	0xbe, 0x05, 0x94, 0x9f, 0xcc, 0x84, 0x5e, 0x3a, 0xbb, 0x76, 0x76, 0x76, 0x1a, 0x99, 0xae, 0xf7,
	0xfe, 0xac, 0x43, 0x3b, 0x25, 0x75, 0xa0, 0x5e, 0x03, 0xe8, 0x2d, 0x34, 0x94, 0x65, 0xa1, 0x83,
	0xeb, 0xb8, 0x2a, 0x27, 0x34, 0x3f, 0x5b, 0xb9, 0xae, 0x85, 0x5d, 0x43, 0xaf, 0xa1, 0x2e, 0xdd,
	0x05, 0x3d, 0xcc, 0xa0, 0x15, 0x4e, 0x66, 0x7e, 0xba, 0x62, 0x35, 0x4b, 0xf3, 0x16, 0x1a, 0xea,
	0x56, 0xe7, 0x6a, 0xaa, 0x74, 0x9c, 0x5c, 0x4d, 0xd5, 0x36, 0xa0, 0x6a, 0x92, 0xac, 0xe5, 0x6a,
	0xaa, 0xd0, 0x56, 0xae, 0xa6, 0xaa, 0xbb, 0x69, 0xd5, 0xd0, 0x29, 0x6c, 0x15, 0xee, 0x0e, 0xda,
	0x5b, 0xb2, 0xa9, 0xd7, 0xf2, 0x8d, 0x69, 0x1e, 0x14, 0x32, 0x2d, 0xdd, 0x35, 0xab, 0x86, 0x7e,
	0x82, 0x86, 0xb2, 0x86, 0x5c, 0x7b, 0x95, 0x06, 0x94, 0x6b, 0x6f, 0x85, 0x97, 0x6c, 0x5f, 0x5d,
	0xee, 0x43, 0xee, 0xd5, 0xf7, 0x02, 0xee, 0xf6, 0x67, 0xb1, 0x60, 0xd3, 0x77, 0x44, 0x9c, 0x33,
	0x6f, 0x65, 0x91, 0x2b, 0xe6, 0xad, 0x1a, 0x7a, 0x0e, 0x6d, 0x75, 0xbc, 0xd7, 0x9d, 0x56, 0x98,
	0x81, 0x59, 0x31, 0x67, 0xd5, 0x4c, 0x2d, 0xdf, 0xde, 0x5f, 0x75, 0xd8, 0x4c, 0x6b, 0xfa, 0x61,
	0x1e, 0xfe, 0x2f, 0xb2, 0x1b, 0x8a, 0xec, 0xec, 0xdf, 0x53, 0x46, 0xfb, 0xea, 0x72, 0x7f, 0x13,
	0x5a, 0x34, 0x14, 0xc3, 0x28, 0x91, 0xc6, 0x2f, 0xd0, 0x52, 0xd0, 0x01, 0x11, 0x68, 0x55, 0x78,
	0xfc, 0xcf, 0xf3, 0xff, 0xc7, 0xd2, 0x6b, 0x5e, 0x5d, 0xee, 0xd7, 0x9b, 0xc6, 0x3d, 0xa3, 0x77,
	0x06, 0x5b, 0xca, 0xf8, 0x52, 0x8b, 0x7b, 0xa9, 0x0f, 0xc7, 0x2c, 0xd0, 0x5f, 0xf0, 0x56, 0xf3,
	0x41, 0xe5, 0x5a, 0x7a, 0x30, 0xa9, 0xb0, 0x4f, 0x4e, 0xce, 0x5e, 0xdc, 0xe4, 0x53, 0xb8, 0xea,
	0xeb, 0xfb, 0xb9, 0x9e, 0x1c, 0x35, 0x12, 0xf4, 0xb3, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3b,
	0x00, 0xfe, 0x05, 0xa4, 0x0b, 0x00, 0x00,
}
